### PR TITLE
Question from CodeChef

### PR DESCRIPTION
**Pull request by divyamJi06**

### CODE REVIEW

**Comment by divyamJi06** [comment]
hey i have added a question from codechef please merge this

**Comment by spdInc** [comment]
> hey i have added a question from codechef please merge this

Please add the question also

**Comment by divyamJi06** [comment]
I have added the question in the java file as a comment.

**Comment by spdInc** [comment]
Hey! please create a codechef directory and then commit/PR. In the codechef directory you must have different section for question and answers

**Pull request closed without merging**
