### PR TITLE
created fibonacci series in java

### PR DESCRIPTION
**Pull request by JainVanshika**

### CODE REVIEW

**Comment by spdInc** [comment]
please create a directory of your topic

**Comment by JainVanshika** [comment]
> please create a directory of your topic

sorry,  I'm new here, so I don't know much about GitHub

**Comment by PrajjwalDy** [comment]
where you write the file name just type your directory name and put "/"  and it will be converted to directory and then enter your file name and commit your file

**Comment by JainVanshika** [comment]
> where you write the file name just type your directory name and put "/" and it will be converted to directory and then enter your file name and commit your file

thank you

**Comment by spdInc** [comment]
Thank you @jainvanshi3105 
Happy Contributing.

**Comment by PrajjwalDy** [comment]
> > where you write the file name just type your directory name and put "/" and it will be converted to directory and then enter your file name and commit your file
> 
> thank you

have you participated in hacktoberfest?

**Comment by JainVanshika** [comment]
> > > where you write the file name just type your directory name and put "/" and it will be converted to directory and then enter your file name and commit your file
> > 
> > 
> > thank you
> 
> have you participated in hacktoberfest?

yes,it's my first time

**Comment by PrajjwalDy** [comment]
> > > > where you write the file name just type your directory name and put "/" and it will be converted to directory and then enter your file name and commit your file
> > > 
> > > 
> > > thank you
> > 
> > have you participated in hacktoberfest?
> 
> yes,it's my first time

Then the best of Luck.
You can connect with me on LinkedIn if you like to do https://www.linkedin.com/in/prajjwal-dubey-7700a0153

**Comment by spdInc** [comment]
Thankyou for the contribution now stop the conversation guys this is not your personal account.

**Pull request merged**
